branches:
  only:
    - master

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%APPDATA%\npm'

install:
  - git submodule update --init --recursive
  - ps: Install-Product node 6 x64
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm prune
  - npm install

before_build:
  - node --version
  - npm --version
  - npm run test

build_script:
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (
      npm run publish-win
    ) ELSE (
      npm run pack
    )

test: off
